add one space to avoid bug in bitbake core-image-weston:
ERROR: Nothing RPROVIDES 'matchbox-terminaledk2-loongarch' (but /home/foxsen/software/poky/meta/recipes-graphics/images/core-image-weston.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'matchbox-terminaledk2-loongarch' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['matchbox-terminaledk2-loongarch']
ERROR: Required build target 'core-image-weston' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-weston', 'matchbox-terminaledk2-loongarch']

Signed-off-by: zhangfuxin <fxzhang@ict.ac.cn>